### ISSUE TITLE
Decide on openchaos.io standard hosting format

### ISSUE THREAD

**Issue by russmiles** [open-chaos/openchaos#11]
Should we begin to develop the standard content in something like mkdocs?

**Comment by russmiles** [comment]
@Lawouach My feeling here is mkdocs would make the simplest transition for reuse from some of the current implementation descriptions under Chaos Toolkit? Not that it would be so closely tied necessarily in the future, but a good first step.

**Comment by Lawouach** [comment]
Hi there,

mkdocs is easy and known so I'm happy with that for sure. Specially if you feel like the content ought to look like a doc website.
If you feel like the content should look more like a regulare website, then something like GridSome/Gatsby would be better.

Ultimately, it doesn't really matter much since it's always something some CSS can fix I suppose.

**Comment by russmiles** [comment]
I think, given the defacto standard goals of this initiative then mkdocs would likely be good enough to get rolling.

**Comment by russmiles** [comment]
We _could_ even use this repo for this content, as it is the accompanying content to the initiative and would avoid a profusion of repositories under the `open-chaos` org? wdyt @Lawouach ?

**Comment by Lawouach** [comment]
It makes sense but it's a little tricky if you intend on keeping the existing declaration page as still the home page of the openchaos.io domain?

**Comment by russmiles** [comment]
It's a good point. Maybe a `standards` repo for these docs? Or individual repos for different aspects, such as `experiment`, `experiment-findings`, `control-api`, `driver-api` and `chaos-service-api` @Lawouach? (those are my first stab at names, nothing more)

**Comment by russmiles** [comment]
Or maybe we simply leverage the RFCs report, https://github.com/open-chaos/rfcs , as it stands and split the various proposed draft standards as markdown or asciidoc across those directories with no need for special mkdocs?

**Comment by Lawouach** [comment]
Agreed. Let's keep the barrier of contribution and PR review low. Let's go for a single repo with directories and markdown files :)

This may help? https://github.com/mmarkdown/mmark

**Comment by russmiles** [comment]
Markdown in the rfcs repository it is!
